apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flask-ingress-generic
  annotations:
        traefik.ingress.kubernetes.io/service-weights: |-
          flask-blue: 70.0
          flask-green: 30.0
spec:
  rules:
    - host: flask.192.168.1.222.xip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: flask-blue
              servicePort: 8080
          - path: /
            backend:
              serviceName: flask-green
              servicePort: 8080
